Enabling spinning a local dev environment with: make, docker-compose …
redhat-exd-rebuilds/estuary pull request #129
Opened 2021-04-05 17:17 UTC by lioramilbaum

…& docker

2021-04-05 17:19 UTC, lioramilbaum commented
@mprahl The image is built but the end point is not accessible on run-time. Can you please take a look?

2021-04-12 20:08 UTC, mprahl commented on Dockerfile
> +CMD ng serve --open
Try this instead:
```suggestion
CMD ng serve --host 0.0.0.0
```

2021-04-12 20:09 UTC, mprahl commented on docker-compose.yml
> +version: '3.9'
Could we please use 3.3 for greater compatibility? That's what my client requires (Fedora 32).

2021-04-12 20:09 UTC, mprahl commented on docker-compose.yml
> +    expose:
I believe this is redundant since it's in the Dockerfile already.

2021-04-12 20:09 UTC, mprahl requested changes
Thanks for the contribution. Just a few small changes.

2021-04-13 10:19 UTC, lioramilbaum commented on Dockerfile
> +CMD ng serve --open
Thanks. That worked.

2021-04-13 12:22 UTC, mprahl requested changes

2021-04-13 12:22 UTC, mprahl commented on Dockerfile
> +CMD ng serve --host 0.0.0.0
Could you add a newline here please?

2021-04-13 12:22 UTC, mprahl commented on Dockerfile
> +FROM registry.redhat.io/ubi8/nodejs-10:latest
Do you think we could rename this Dockerfile to indicate that it's for development only and not for production use? For instance, we can call it `Dockerfile-dev` or something.

2021-04-13 14:05 UTC, mprahl commented on README.md
> +### Prerequests
```suggestion
### Prerequisites
```

2021-04-13 14:05 UTC, mprahl requested changes
Just one typo to fix. Sorry I missed this in the last review.

2021-04-13 19:49 UTC, mprahl approved these changes

2021-04-13 19:49 UTC, merged